export const games = [
  {
    slug: "sunset-shell-run",
    title: "Sunset Shell Run",
    description: "Bright platform adventure with bosses, upgrades, stars, and a world map.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\eyevinn\\summer-platformer-ai",
    repoName: "sunset-shell-run",
    github: "https://github.com/NoelPerland/sunset-shell-run",
    deployUrl: "https://pure-soil-summerplatformerai.apps.liivo.io",
    thumbnail: "/assets/thumbs/sunset-shell-run.png",
    accent: "#ffb347"
  },
  {
    slug: "age-of-war-lite",
    title: "Age of War-lite",
    description: "Lane-battle tactics with evolving tech, units, economy, and clear win states.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Desktop\\eyevinn\\age-of-war-lite",
    repoName: "age-of-war-lite",
    github: "https://github.com/NoelPerland/age-of-war-lite",
    deployUrl: "https://flyby-copse-noelsgamehub.apps.liivo.io/games/age-of-war-lite/",
    thumbnail: "/assets/thumbs/age-of-war-lite.png",
    accent: "#ffd166"
  },
  {
    slug: "circuit-courier",
    title: "Circuit Courier",
    description: "Neon courier runs with dashes, drones, mines, combos, and score chasing.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Documents\\Codex\\2026-05-27\\can-you-update-my-cv-and\\circuit-courier",
    repoName: "circuit-courier",
    github: "https://github.com/NoelPerland/circuit-courier",
    deployUrl: "https://gale-brood-circuitcourier.apps.liivo.io",
    thumbnail: "/assets/thumbs/circuit-courier.png",
    accent: "#00e5ff"
  },
  {
    slug: "aero-leap",
    title: "Stunt Machine / Aero Leap",
    description: "Flash-style stunt launcher with physics, upgrades, distance scoring, and crashes.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Desktop\\eyevinn\\stunt-game",
    repoName: "aero-leap",
    github: "https://github.com/NoelPerland/aero-leap",
    deployUrl: "https://narrow-nook-stuntmachine.apps.liivo.io",
    thumbnail: "/assets/thumbs/aero-leap-redesign.jpg",
    accent: "#ff6b6b"
  },
  {
    slug: "neon-invader",
    title: "Neon Invader",
    description: "Space shooter with wave pressure, powerups, clean collision, and score flow.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Desktop\\eyevinn\\space-invaders",
    repoName: "neon-invader",
    github: "https://github.com/NoelPerland/neon-invader",
    deployUrl: "https://dark-grove-neoninvader.apps.liivo.io",
    thumbnail: "/assets/thumbs/neon-invader.png",
    accent: "#7c5cff"
  },
  {
    slug: "bomb-blitz-arena",
    title: "Bomb Blitz Arena",
    description: "Bomber arena with bots, tight loops, smoke-test hooks, and Phaser scene flow.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Desktop\\eyevinn\\bomber-man",
    repoName: "bomb-blitz-arena",
    github: "https://github.com/NoelPerland/bomb-blitz-arena",
    deployUrl: "https://rush-plum-bombblitzlive.apps.liivo.io",
    thumbnail: "/assets/thumbs/bomb-blitz-arena.png",
    accent: "#ff3d81"
  },
  {
    slug: "cube-attack",
    title: "Cube Attack",
    description: "Compact runner with obstacle timing, crisp UI, level flow, and fast retries.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Desktop\\eyevinn\\cube-attack",
    repoName: "cube-attack",
    github: "https://github.com/NoelPerland/cube-attack",
    deployUrl: "https://cubeattack.apps.liivo.io",
    thumbnail: "/assets/thumbs/cube-attack.png",
    accent: "#45ff9a"
  },
  {
    slug: "balloon-rush",
    title: "Balloon Rush",
    description: "Bloons-style tower defense with winding lanes, towers, upgrades, waves, and balloon pops.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Documents\\Codex\\2026-05-07\\we-have-created-many-game-what",
    repoName: "balloon-rush",
    github: "https://github.com/NoelPerland/balloon-rush",
    deployUrl: "https://dust-teal-balloonrush.apps.liivo.io",
    thumbnail: "/assets/thumbs/balloon-rush.jpg",
    accent: "#9cff3b"
  },
  {
    slug: "relic-grove-archive-frontier",
    title: "Relic Grove: Archive Frontier",
    description: "Top-down RPG slice with combat, gathering, inventory, upgrades, and boss clearing.",
    status: "prototype",
    engine: "Canvas",
    localPath: "C:\\Users\\LENOVO\\Documents\\Codex\\2026-05-28\\caveman-c-users-lenovo-codex-skills",
    repoName: "relic-grove-archive-frontier",
    github: "https://github.com/NoelPerland/relic-grove-archive-frontier",
    deployUrl: "https://flyby-copse-noelsgamehub.apps.liivo.io/games/relic-grove-archive-frontier/",
    thumbnail: "/assets/thumbs/relic-grove-archive-frontier.png",
    accent: "#b7ff5a"
  }
];
