export const games = [
  {
    slug: "sunset-shell-run",
    title: "Sunset Shell Run",
    description: "Bright platform adventure with bosses, upgrades, stars, and a world map.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\eyevinn\\summer-platformer-ai",
    repoName: "sunset-shell-run",
    github: "Needs GitHub repo",
    deployUrl: "https://pure-soil-summerplatformerai.apps.liivo.io",
    thumbnail: "/assets/thumbs/sunset-shell-run.png",
    accent: "#ffb347"
  },
  {
    slug: "age-of-war-lite",
    title: "Age of War-lite",
    description: "Lane-battle tactics with evolving tech, units, economy, and clear win states.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Desktop\\eyevinn\\age-of-war-lite",
    repoName: "age-of-war-lite",
    github: "Needs GitHub repo",
    deployUrl: "",
    thumbnail: "/assets/thumbs/age-of-war-lite.png",
    accent: "#ffd166"
  },
  {
    slug: "circuit-courier",
    title: "Circuit Courier",
    description: "Neon courier runs with dashes, drones, mines, combos, and score chasing.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Documents\\Codex\\2026-05-27\\can-you-update-my-cv-and\\circuit-courier",
    repoName: "circuit-courier",
    github: "Needs GitHub repo",
    deployUrl: "",
    thumbnail: "/assets/thumbs/circuit-courier.png",
    accent: "#00e5ff"
  },
  {
    slug: "aero-leap",
    title: "Stunt Machine / Aero Leap",
    description: "Flash-style stunt launcher with physics, upgrades, distance scoring, and crashes.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Desktop\\eyevinn\\stunt-game",
    repoName: "aero-leap",
    github: "Needs GitHub repo",
    deployUrl: "https://narrow-nook-stuntmachine.apps.liivo.io",
    thumbnail: "/assets/thumbs/aero-leap.png",
    accent: "#ff6b6b"
  },
  {
    slug: "neon-invader",
    title: "Neon Invader",
    description: "Space shooter with wave pressure, powerups, clean collision, and score flow.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Desktop\\eyevinn\\space-invaders",
    repoName: "neon-invader",
    github: "https://github.com/NoelPerland/neon-invader",
    deployUrl: "https://dark-grove-neoninvader.apps.liivo.io",
    thumbnail: "/assets/thumbs/neon-invader.png",
    accent: "#7c5cff"
  },
  {
    slug: "bomb-blitz-arena",
    title: "Bomb Blitz Arena",
    description: "Bomber arena with bots, tight loops, smoke-test hooks, and Phaser scene flow.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Desktop\\eyevinn\\bomber-man",
    repoName: "bomb-blitz-arena",
    github: "Needs GitHub repo",
    deployUrl: "",
    thumbnail: "/assets/thumbs/bomb-blitz-arena.png",
    accent: "#ff3d81"
  },
  {
    slug: "cube-attack",
    title: "Cube Attack",
    description: "Compact runner with obstacle timing, crisp UI, level flow, and fast retries.",
    status: "playable",
    engine: "Phaser",
    localPath: "C:\\Users\\LENOVO\\Desktop\\eyevinn\\cube-attack",
    repoName: "cube-attack",
    github: "https://github.com/NoelPerland/cube-attack",
    deployUrl: "https://cubeattack.apps.liivo.io",
    thumbnail: "/assets/thumbs/cube-attack.png",
    accent: "#45ff9a"
  },
  {
    slug: "boxline-siege",
    title: "Boxline Siege",
    description: "Canvas survival shooter with waves, pickups, weapons, and boss pressure.",
    status: "prototype",
    engine: "Canvas",
    localPath: "C:\\Users\\LENOVO\\Documents\\Codex\\2026-05-19\\what-are-the-top-5-easiest",
    repoName: "boxline-siege",
    github: "Needs GitHub repo",
    deployUrl: "",
    thumbnail: "/assets/thumbs/boxline-siege.png",
    accent: "#ffa24c"
  },
  {
    slug: "relic-grove-archive-frontier",
    title: "Relic Grove: Archive Frontier",
    description: "Top-down RPG slice with combat, gathering, inventory, upgrades, and boss clearing.",
    status: "prototype",
    engine: "Canvas",
    localPath: "C:\\Users\\LENOVO\\Documents\\Codex\\2026-05-28\\caveman-c-users-lenovo-codex-skills",
    repoName: "relic-grove-archive-frontier",
    github: "Needs GitHub repo",
    deployUrl: "",
    thumbnail: "/assets/thumbs/relic-grove-archive-frontier.png",
    accent: "#b7ff5a"
  }
];
